//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace velowrench.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Languages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Languages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("velowrench.Resources.Languages", typeof(Languages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axle and Hub Standard Checker.
        /// </summary>
        public static string AxleAndHubStandardChecker {
            get {
                return ResourceManager.GetString("AxleAndHubStandardChecker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chain Length Calculator.
        /// </summary>
        public static string ChainLengthCalculator {
            get {
                return ResourceManager.GetString("ChainLengthCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chainline Calculator.
        /// </summary>
        public static string ChainlineCalculator {
            get {
                return ResourceManager.GetString("ChainlineCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compatibility &amp; Standards.
        /// </summary>
        public static string CompatibilityAndStandards {
            get {
                return ResourceManager.GetString("CompatibilityAndStandards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component Compatibility Guide.
        /// </summary>
        public static string ComponentCompatibilityGuide {
            get {
                return ResourceManager.GetString("ComponentCompatibilityGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drivetrain Ratio Calculator.
        /// </summary>
        public static string DrivetrainRatioCalculator {
            get {
                return ResourceManager.GetString("DrivetrainRatioCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rollout Calculator.
        /// </summary>
        public static string RolloutCalculator {
            get {
                return ResourceManager.GetString("RolloutCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spoke Length Calculator.
        /// </summary>
        public static string SpokeLengthCalculator {
            get {
                return ResourceManager.GetString("SpokeLengthCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spoke Tension Guide.
        /// </summary>
        public static string SpokeTensionGuide {
            get {
                return ResourceManager.GetString("SpokeTensionGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transmission &amp; Drivetrain.
        /// </summary>
        public static string TransmissionAndDrivetrain {
            get {
                return ResourceManager.GetString("TransmissionAndDrivetrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wheels &amp; Spoking.
        /// </summary>
        public static string WheelsAndSpoking {
            get {
                return ResourceManager.GetString("WheelsAndSpoking", resourceCulture);
            }
        }
    }
}
