//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace velowrench.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Languages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Languages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("velowrench.UI.Resources.Languages", typeof(Languages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axle and Hub Standard Checker.
        /// </summary>
        public static string AxleAndHubStandardChecker {
            get {
                return ResourceManager.GetString("AxleAndHubStandardChecker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build configuration.
        /// </summary>
        public static string BuildConfiguration {
            get {
                return ResourceManager.GetString("BuildConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadence.
        /// </summary>
        public static string Cadence {
            get {
                return ResourceManager.GetString("Cadence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to = cadence in revolutions per minute.
        /// </summary>
        public static string CadenceRpmFormula {
            get {
                return ResourceManager.GetString("CadenceRpmFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculated.
        /// </summary>
        public static string Calculated {
            get {
                return ResourceManager.GetString("Calculated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation failed.
        /// </summary>
        public static string CalculationFailed {
            get {
                return ResourceManager.GetString("CalculationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation in progress....
        /// </summary>
        public static string CalculationInProgress {
            get {
                return ResourceManager.GetString("CalculationInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculations.
        /// </summary>
        public static string Calculations {
            get {
                return ResourceManager.GetString("Calculations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chain length.
        /// </summary>
        public static string ChainLength {
            get {
                return ResourceManager.GetString("ChainLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chain Length Calculator.
        /// </summary>
        public static string ChainLengthCalculator {
            get {
                return ResourceManager.GetString("ChainLengthCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate the recommended bicycle chain length using your bike&apos;s chain stay length and gear sizes..
        /// </summary>
        public static string ChainLengthCalculatorHeader {
            get {
                return ResourceManager.GetString("ChainLengthCalculatorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chain length:.
        /// </summary>
        public static string ChainLengthLabel {
            get {
                return ResourceManager.GetString("ChainLengthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chain links.
        /// </summary>
        public static string ChainLinks {
            get {
                return ResourceManager.GetString("ChainLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chain links:.
        /// </summary>
        public static string ChainLinksLabel {
            get {
                return ResourceManager.GetString("ChainLinksLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chainring(s) teeth.
        /// </summary>
        public static string ChainringTeeth {
            get {
                return ResourceManager.GetString("ChainringTeeth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chain stay length.
        /// </summary>
        public static string ChainStayLength {
            get {
                return ResourceManager.GetString("ChainStayLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compatibility &amp; Standards.
        /// </summary>
        public static string CompatibilityAndStandards {
            get {
                return ResourceManager.GetString("CompatibilityAndStandards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component Compatibility Guide.
        /// </summary>
        public static string ComponentCompatibilityGuide {
            get {
                return ResourceManager.GetString("ComponentCompatibilityGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crank length.
        /// </summary>
        public static string CrankLength {
            get {
                return ResourceManager.GetString("CrankLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to = crank length.
        /// </summary>
        public static string CrankLengthFormula {
            get {
                return ResourceManager.GetString("CrankLengthFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development.
        /// </summary>
        public static string Development {
            get {
                return ResourceManager.GetString("Development", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development calculation that measures the distance traveled per pedal revolution..
        /// </summary>
        public static string DevelopmentDescription {
            get {
                return ResourceManager.GetString("DevelopmentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to = development.
        /// </summary>
        public static string DevelopmentFormula {
            get {
                return ResourceManager.GetString("DevelopmentFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the values.
        /// </summary>
        public static string EnterValues {
            get {
                return ResourceManager.GetString("EnterValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to = number of teeth on the front chainring.
        /// </summary>
        public static string FrontChainringTeethFormula {
            get {
                return ResourceManager.GetString("FrontChainringTeethFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gain ratio.
        /// </summary>
        public static string GainRatio {
            get {
                return ResourceManager.GetString("GainRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Universal mechanical comparison between bikes. More mechanically accurate than gear inches..
        /// </summary>
        public static string GainRatioDescription {
            get {
                return ResourceManager.GetString("GainRatioDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gear Calculator.
        /// </summary>
        public static string GearCalculator {
            get {
                return ResourceManager.GetString("GearCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualize your gear setup with different metrics: gear inches, gain ratio, development, and speed..
        /// </summary>
        public static string GearCalculatorHeader {
            get {
                return ResourceManager.GetString("GearCalculatorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Represents the different ways of expressing the gear/transmission ratio..
        /// </summary>
        public static string GearCalculatorOutputFormatDescription {
            get {
                return ResourceManager.GetString("GearCalculatorOutputFormatDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All results contain the values calculated for each combination of sprocket and chainring, sorted by chainring size and sprocket size..
        /// </summary>
        public static string GearCalculatorResultsDescription {
            get {
                return ResourceManager.GetString("GearCalculatorResultsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The results of the development and speed calculations can be converted into different units, while the results of the gear inches calculation are only expressed in inches and those of the gain ratio are unitless..
        /// </summary>
        public static string GearCalculatorUnitsDescription {
            get {
                return ResourceManager.GetString("GearCalculatorUnitsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gear inches.
        /// </summary>
        public static string GearInches {
            get {
                return ResourceManager.GetString("GearInches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traditional gear inches calculation. Standard measurement for comparing gear ratios across different bicycle configurations..
        /// </summary>
        public static string GearInchesDescription {
            get {
                return ResourceManager.GetString("GearInchesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This tool uses two common methods to estimate the correct bicycle chain length:.
        /// </summary>
        public static string HelpChainLengthCalculationHeader {
            get {
                return ResourceManager.GetString("HelpChainLengthCalculationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The distance between the center of the bottom bracket (pedal axle) and the center of the rear wheel axle. It is usually measured along the chain line..
        /// </summary>
        public static string HelpChainStayLength {
            get {
                return ResourceManager.GetString("HelpChainStayLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chain stay length (C).
        /// </summary>
        public static string HelpChainStayLengthHeader {
            get {
                return ResourceManager.GetString("HelpChainStayLengthHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of teeth on your bike&apos;s largest front chainring..
        /// </summary>
        public static string HelpFrontChainring {
            get {
                return ResourceManager.GetString("HelpFrontChainring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Largest front chainring (F).
        /// </summary>
        public static string HelpFrontChainringHeader {
            get {
                return ResourceManager.GetString("HelpFrontChainringHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of teeth on the largest cog of your rear cassette/freewheel..
        /// </summary>
        public static string HelpLargestRearSprocket {
            get {
                return ResourceManager.GetString("HelpLargestRearSprocket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Largest rear sprocket (R).
        /// </summary>
        public static string HelpLargestRearSprocketHeader {
            get {
                return ResourceManager.GetString("HelpLargestRearSprocketHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hub measurements.
        /// </summary>
        public static string HubMeasurements {
            get {
                return ResourceManager.GetString("HubMeasurements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inputs.
        /// </summary>
        public static string Inputs {
            get {
                return ResourceManager.GetString("Inputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Largest front chainring.
        /// </summary>
        public static string LargestFrontChainring {
            get {
                return ResourceManager.GetString("LargestFrontChainring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Largest rear sprocket.
        /// </summary>
        public static string LargestRearSprocket {
            get {
                return ResourceManager.GetString("LargestRearSprocket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output format.
        /// </summary>
        public static string OutputFormat {
            get {
                return ResourceManager.GetString("OutputFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to = number of teeth on the rear sprocket.
        /// </summary>
        public static string RearSprocketTeethFormula {
            get {
                return ResourceManager.GetString("RearSprocketTeethFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended value.
        /// </summary>
        public static string RecommendedValue {
            get {
                return ResourceManager.GetString("RecommendedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both formulas give the recommended chain length, which can then be converted into the number of links required..
        /// </summary>
        public static string ResultChainLengthCalculExplaination {
            get {
                return ResourceManager.GetString("ResultChainLengthCalculExplaination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string Results {
            get {
                return ResourceManager.GetString("Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rigorous formula.
        /// </summary>
        public static string RigorousFormula {
            get {
                return ResourceManager.GetString("RigorousFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A more accurate method that uses Pythagoras&apos; theorem to take into account the actual path of the chain around the gears. This is more accurate for shorter chainstays or bikes with unusual gear sizes..
        /// </summary>
        public static string RigorousFormulaExplanation {
            get {
                return ResourceManager.GetString("RigorousFormulaExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rim measurements.
        /// </summary>
        public static string RimMeasurements {
            get {
                return ResourceManager.GetString("RimMeasurements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple formula.
        /// </summary>
        public static string SimpleFormula {
            get {
                return ResourceManager.GetString("SimpleFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A quick approximation based on chainstay length and the sizes of your largest front chainring and largest rear sprocket. Best suited for standard bikes and quick calculations..
        /// </summary>
        public static string SimpleFormulaExplanation {
            get {
                return ResourceManager.GetString("SimpleFormulaExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong.
        /// </summary>
        public static string SomethingWentWrong {
            get {
                return ResourceManager.GetString("SomethingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        public static string Speed {
            get {
                return ResourceManager.GetString("Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculates the speed achievable at a specific pedaling rate (RPM)..
        /// </summary>
        public static string SpeedDescription {
            get {
                return ResourceManager.GetString("SpeedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spoke Length Calculator.
        /// </summary>
        public static string SpokeLengthCalculator {
            get {
                return ResourceManager.GetString("SpokeLengthCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spoke Tension Guide.
        /// </summary>
        public static string SpokeTensionGuide {
            get {
                return ResourceManager.GetString("SpokeTensionGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprocket(s) teeth.
        /// </summary>
        public static string SprocketTeeth {
            get {
                return ResourceManager.GetString("SprocketTeeth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teeth.
        /// </summary>
        public static string Teeth {
            get {
                return ResourceManager.GetString("Teeth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transmission &amp; Drivetrain.
        /// </summary>
        public static string TransmissionAndDrivetrain {
            get {
                return ResourceManager.GetString("TransmissionAndDrivetrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to veloWrench.
        /// </summary>
        public static string VeloWrench {
            get {
                return ResourceManager.GetString("VeloWrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to = wheel circumference.
        /// </summary>
        public static string WheelCircumferenceFormula {
            get {
                return ResourceManager.GetString("WheelCircumferenceFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to = wheel diameter in inches.
        /// </summary>
        public static string WheelDiameterFormula {
            get {
                return ResourceManager.GetString("WheelDiameterFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to = wheel radius.
        /// </summary>
        public static string WheelRadiusFormula {
            get {
                return ResourceManager.GetString("WheelRadiusFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wheels &amp; Spoking.
        /// </summary>
        public static string WheelsAndSpoking {
            get {
                return ResourceManager.GetString("WheelsAndSpoking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wheel size.
        /// </summary>
        public static string WheelSize {
            get {
                return ResourceManager.GetString("WheelSize", resourceCulture);
            }
        }
    }
}
