<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AnalysisLevel>latest-all</AnalysisLevel>
		<AnalysisMode>AllEnabledByDefault</AnalysisMode>
		<EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild>
		<EnableNETAnalyzers>True</EnableNETAnalyzers>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
	</PropertyGroup>

	<ItemGroup>
	  <EditorConfigFiles Remove="C:\Workspaces\velowrench\velowrench.Utils\.editorconfig" />
	</ItemGroup>

	<ItemGroup>
	  <None Include="C:\Workspaces\velowrench\velowrench.Utils\.editorconfig" />
	</ItemGroup>

</Project>
